version: "3.5"
services:
  aniversario:
    container_name: aniversario
    image: aniversario-image:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "13003:8080"
    environment:
      - "TZ=America/Lima"
